# -*- coding: utf-8 -*-
"""dmax=1 sindy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B27rF07VYzh-vjxv8zwerSNe-s720B_m
"""

#!/usr/bin/env python3
# Graph-only SINDy pipeline with STLSQ
# - infer only the graph from linear terms
# - add triangles afterward via clique closure
# - use AVERAGE score, not max
#     edge score:     (|j->i| + |i->j|)/2
#     triangle score: average of its 3 edge scores

import os
import math
import time
from itertools import combinations

import numpy as np
import pandas as pd
from scipy.signal import savgol_filter

try:
    import cupy as cp
    GPU_AVAILABLE = True
    print("✓ GPU (CuPy) detected")
    _ = cp.zeros(1)
except ImportError:
    GPU_AVAILABLE = False
    cp = np
    print("⚠️ GPU not available (using NumPy)")

xp = cp if GPU_AVAILABLE else np


# ============================================================
# -------------------- GROUND TRUTH ---------------------------
# ============================================================

GT_EDGES_INLINE = {
    frozenset((0, 1)), frozenset((0, 2)), frozenset((0, 3)), frozenset((1, 2)),
    frozenset((2, 3)), frozenset((2, 8)), frozenset((2, 9)),
    frozenset((3, 4)), frozenset((3, 5)), frozenset((4, 5)),
    frozenset((5, 6)), frozenset((5, 8)), frozenset((5, 9)),
    frozenset((6, 7)), frozenset((6, 8)), frozenset((7, 8)),
    frozenset((7, 9)), frozenset((8, 9)),
}

GT_TRIS_INLINE = {
    frozenset((0, 1, 2)),
    frozenset((3, 4, 5)),
    frozenset((7, 8, 9)),
    frozenset((6, 7, 8)),
    frozenset((2, 8, 9)),
}


# ============================================================
# --------------------- PARAMETERS ----------------------------
# ============================================================

CSV_FILE = "polynomial_network_v2_high_interaction.csv"

FS = 256.0
WIN_SG = 29
ORDER = 3

# Graph-only model
D_MAX = 1

WIN_LEN = 5120
STRIDE = WIN_LEN
MAX_ROWS = 6000

R_TARGET_PC = 0.95
K_MIN = 600
K_MAX = 1000000

OUTDIR = "dyn_graph_stlsq_clique"
os.makedirs(OUTDIR, exist_ok=True)

# STLSQ hyperparameters
RIDGE_LAMBDA = 1e-3
STLSQ_ITERS = 10

# Thresholding sweep
EDGE_QS = np.linspace(0.30, 0.99, 15)

# Numerical thresholds
ROW_NORM_NNZ_THR = 1e-6
PARAM_ABS_NNZ_THR = 1e-8


# ============================================================
# -------------------- HELPER FUNCTIONS -----------------------
# ============================================================

def to_numpy(x):
    return cp.asnumpy(x) if GPU_AVAILABLE else x


def precompute_linear_maps(n):
    """
    For D_MAX=1 only:
      row 0 = constant
      row 1..n = linear features x_0,...,x_{n-1}
    """
    maps = {1: {}}
    row = 0
    for i in range(n):
        row += 1
        maps[1][(i,)] = row
    g_total = row + 1
    return maps, g_total


def build_library_linear(XT):
    """
    XT shape: (T, n)
    Returns Theta shape: (T, 1+n)
    """
    T = XT.shape[0]
    ones = xp.ones((T, 1), dtype=XT.dtype)
    return xp.concatenate([ones, XT], axis=1)


def precompute_gram(Theta_std, Y_scaled):
    """
    G = Theta^T Theta / T
    B = Theta^T Y / T
    """
    T = max(1, Theta_std.shape[0])
    G = (Theta_std.T @ Theta_std) / T
    eps_ridge = 5e-3
    G = G + eps_ridge * xp.eye(G.shape[0], dtype=G.dtype)
    B = (Theta_std.T @ Y_scaled) / T
    return G, B


def select_local(Xw):
    """
    Same robust local selection logic as your original code.
    """
    x0 = np.median(Xw, axis=1, keepdims=True)
    Xc = Xw - x0
    sigma = np.maximum(
        1e-8,
        1.4826 * np.median(
            np.abs(Xc - np.median(Xc, axis=1, keepdims=True)),
            axis=1,
            keepdims=True
        )
    )
    d_pc = np.sqrt(((Xc / sigma) ** 2).sum(axis=0)) / np.sqrt(Xc.shape[0])
    keep = np.where(d_pc <= R_TARGET_PC)[0]

    if keep.size < K_MIN:
        keep = np.argsort(d_pc)[:K_MIN]
    elif keep.size > K_MAX:
        keep = np.argsort(d_pc)[:K_MAX]

    return x0, np.sort(keep), d_pc


def solve_stlsq(G, B, lam_ridge=1e-3, thr=1e-2, n_iter=8, keep_const=True):
    """
    Sequential Thresholded Least Squares on Gram system.

    Solves:
        Y ≈ Theta Xi
    using:
        initial ridge fit
        repeated threshold + refit on support

    Inputs:
        G: (g, g)
        B: (g, n_targets)
    Returns:
        Xi: (g, n_targets)
    """
    g, n_targets = B.shape
    I = xp.eye(g, dtype=G.dtype)

    # Initial ridge fit
    Xi = xp.linalg.solve(G + lam_ridge * I, B)

    for _ in range(n_iter):
        Xi_old = Xi.copy()

        for col in range(n_targets):
            support = xp.abs(Xi[:, col]) >= thr
            if keep_const:
                support[0] = True

            idx = xp.where(support)[0]
            if idx.size == 0:
                continue

            Gs = G[xp.ix_(idx, idx)]
            Bs = B[idx, col]
            sol = xp.linalg.solve(
                Gs + lam_ridge * xp.eye(len(idx), dtype=G.dtype),
                Bs
            )

            Xi[:, col] = 0
            Xi[idx, col] = sol

        diff = float(xp.linalg.norm(Xi - Xi_old))
        if diff < 1e-6:
            break

    return Xi


def refit_on_support(G, B, Xi, lam_ridge=1e-6, keep_const=True):
    """
    Debias/refit after STLSQ on the discovered support.
    Column-wise support refit.
    """
    g, n_targets = B.shape
    Xi_refit = xp.zeros_like(Xi)

    for col in range(n_targets):
        support = xp.abs(Xi[:, col]) > 0
        if keep_const:
            support[0] = True

        idx = xp.where(support)[0]
        if idx.size == 0:
            continue

        Gs = G[xp.ix_(idx, idx)]
        Bs = B[idx, col]
        sol = xp.linalg.solve(
            Gs + lam_ridge * xp.eye(len(idx), dtype=G.dtype),
            Bs
        )
        Xi_refit[idx, col] = sol

    return Xi_refit


def readout_graph_scores_avg(Xi, n):
    """
    Xi has shape (1+n, n), where:
      row 0      = constant
      row 1 + j  = source node j
      column i   = target node i

    directed score j -> i = |Xi[1+j, i]|

    undirected edge score = average of the two directed magnitudes:
        S2(i,j) = (|j->i| + |i->j|)/2
    """
    A = to_numpy(Xi)
    absA = np.abs(A)

    S2_dir = np.zeros((n, n), dtype=np.float64)
    for src in range(n):
        row = 1 + src
        for tgt in range(n):
            if src == tgt:
                continue
            S2_dir[src, tgt] = absA[row, tgt]

    S2 = np.zeros((n, n), dtype=np.float64)
    for i in range(n):
        for j in range(i + 1, n):
            s = 0.5 * (S2_dir[i, j] + S2_dir[j, i])
            S2[i, j] = s
            S2[j, i] = s

    return S2, S2_dir


def sweep_edge_thresholds(S2, gt_edges_set, qs=np.linspace(0.30, 0.99, 15)):
    """
    Threshold sweep for graph edges.
    """
    nloc = S2.shape[0]
    vals = [S2[i, j] for i in range(nloc) for j in range(i + 1, nloc) if S2[i, j] > 0]
    out = []

    if not vals:
        return out

    vals = np.array(vals, dtype=np.float64)

    for q in qs:
        tau2 = float(np.quantile(vals, q))
        pred = {
            frozenset((i, j))
            for i in range(nloc)
            for j in range(i + 1, nloc)
            if S2[i, j] >= tau2
        }

        TP = len(pred & gt_edges_set)
        FP = len(pred - gt_edges_set)
        FN = len(gt_edges_set - pred)

        P = TP / (TP + FP) if (TP + FP) > 0 else 0.0
        R = TP / (TP + FN) if (TP + FN) > 0 else 0.0
        F1 = 2 * P * R / (P + R) if (P + R) > 0 else 0.0

        out.append({
            "q": float(q),
            "tau2": tau2,
            "P": P,
            "R": R,
            "F1": F1,
            "n_edges": len(pred),
        })

    return out


def build_clique_complex_from_graph(S2, tau2):
    """
    Given edge-score matrix S2 and threshold tau2:
      - keep edges with S2[i,j] >= tau2
      - add triangles whenever all 3 edges are present
      - triangle score = average of the 3 edge scores
    """
    n = S2.shape[0]

    pred_edges = set()
    edge_scores = {}

    for i in range(n):
        for j in range(i + 1, n):
            s = float(S2[i, j])
            if s >= tau2:
                e = frozenset((i, j))
                pred_edges.add(e)
                edge_scores[e] = s

    pred_tris = set()
    tri_scores = {}

    for i in range(n):
        for j in range(i + 1, n):
            e1 = frozenset((i, j))
            if e1 not in pred_edges:
                continue
            for k in range(j + 1, n):
                e2 = frozenset((i, k))
                e3 = frozenset((j, k))
                if e2 in pred_edges and e3 in pred_edges:
                    tri = frozenset((i, j, k))
                    pred_tris.add(tri)
                    tri_scores[tri] = (edge_scores[e1] + edge_scores[e2] + edge_scores[e3]) / 3.0

    return pred_edges, edge_scores, pred_tris, tri_scores


def evaluate_set_prediction(pred_set, gt_set):
    TP = len(pred_set & gt_set)
    FP = len(pred_set - gt_set)
    FN = len(gt_set - pred_set)

    P = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    R = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    F1 = 2 * P * R / (P + R) if (P + R) > 0 else 0.0

    return {
        "TP": TP,
        "FP": FP,
        "FN": FN,
        "P": P,
        "R": R,
        "F1": F1,
    }


def nnz_summary(Xi):
    A = to_numpy(Xi)
    row_norms = np.linalg.norm(A, axis=1)
    return {
        "nnz_rows": int(np.sum(row_norms > ROW_NORM_NNZ_THR)),
        "nnz_params": int(np.sum(np.abs(A) > PARAM_ABS_NNZ_THR)),
    }


# ============================================================
# ---------------------- LOAD DATA ---------------------------
# ============================================================

print("\n📂 Loading data...")
if not os.path.exists(CSV_FILE):
    print(f"❌ Error: Data file '{CSV_FILE}' not found.")
    raise SystemExit(1)

#raw = pd.read_csv(CSV_FILE, header=None).values.astype(np.float64)

# Drop degenerate channels
#raw = raw[:, np.ptp(raw, axis=0) > 1e-12].T
from nilearn import datasets
from pathlib import Path
data_dir = Path.cwd()
abide = datasets.fetch_abide_pcp(data_dir=str(data_dir), derivatives="rois_cc200", n_subjects=1)
all_timeseries = abide.rois_cc200
ts_data = all_timeseries[0]
raw = ts_data.T
n, T_raw = raw.shape
dt = 1.0 / FS
print(f"✓ {n} channels × {T_raw} samples ({T_raw / FS:.1f}s)")

half = (WIN_SG - 1) // 2

X_smooth = savgol_filter(raw, WIN_SG, ORDER, axis=1, mode="interp")[:, half:-half]
dXdt_raw = savgol_filter(raw, WIN_SG, ORDER, deriv=1, delta=dt, axis=1, mode="interp")[:, half:-half]

mu = X_smooth.mean(axis=1, keepdims=True)
sig = X_smooth.std(axis=1, keepdims=True) + 1e-8

X = (X_smooth - mu) / sig
Y = dXdt_raw / sig

X_gpu = cp.asarray(X) if GPU_AVAILABLE else X
Y_gpu = cp.asarray(Y) if GPU_AVAILABLE else Y

print(f"✓ Data on {'GPU' if GPU_AVAILABLE else 'CPU'}")


# ============================================================
# --------------------- SINGLE WINDOW ------------------------
# ============================================================

print("\n🔍 Preparing single full-length window...")

w_start = 0
w_end = WIN_LEN

Xw_full = X[:, w_start:w_end]
x0_full, keep_full, d_pc_full = select_local(Xw_full)

meta = {
    "w_start": w_start,
    "t_mid": (w_start + WIN_LEN / 2) * dt,
    "x0": x0_full.flatten(),
    "keep": keep_full,
}

print("✓ 1 window ready (entire dataset)")


# ============================================================
# ---------------- PRECOMPUTE LINEAR STRUCTURE ----------------
# ============================================================

print("\n⚙️  Precomputing linear maps...")
maps0, g_total = precompute_linear_maps(n)
print(f"✓ g_total={g_total} rows (D_MAX={D_MAX})")


# ============================================================
# ------------- BUILD LINEAR LIBRARY / GRAM ONCE -------------
# ============================================================

print("\n🧱 Building linear library and Gram matrices...")

w_start = meta["w_start"]
w_end = meta["w_start"] + WIN_LEN

if GPU_AVAILABLE:
    Xw = X_gpu[:, w_start:w_end]
    Yw = Y_gpu[:, w_start:w_end]

    x0 = cp.asarray(meta["x0"].reshape(-1, 1))
    Xw_c = Xw - x0

    Xw_use = Xw_c[:, meta["keep"]]
    Yw_use = Yw[:, meta["keep"]]

    if Xw_use.shape[1] > MAX_ROWS:
        idx = cp.linspace(0, Xw_use.shape[1] - 1, MAX_ROWS, dtype=cp.int32)
        Xw_use = Xw_use[:, idx]
        Yw_use = Yw_use[:, idx]

    XT = Xw_use.T
    YT = Yw_use.T
else:
    Xw = X[:, w_start:w_end]
    Yw = Y[:, w_start:w_end]

    x0 = meta["x0"].reshape(-1, 1)
    Xw_c = Xw - x0

    Xw_use = Xw_c[:, meta["keep"]]
    Yw_use = Yw[:, meta["keep"]]

    if Xw_use.shape[1] > MAX_ROWS:
        idx = np.linspace(0, Xw_use.shape[1] - 1, MAX_ROWS, dtype=int)
        Xw_use = Xw_use[:, idx]
        Yw_use = Yw_use[:, idx]

    XT = Xw_use.T
    YT = Yw_use.T

Theta = build_library_linear(XT)

Theta_mean = xp.mean(Theta, axis=0, keepdims=True)
Theta_stdv = xp.std(Theta, axis=0, keepdims=True) + 1e-8
Thetaz = (Theta - Theta_mean) / Theta_stdv

Y_mean = xp.mean(YT, axis=0, keepdims=True)
Y_stdv = xp.std(YT, axis=0, keepdims=True) + 1e-8
Y_scaled = (YT - Y_mean) / Y_stdv

Thetaz = Thetaz.astype(xp.float32, copy=False)
Y_scaled = Y_scaled.astype(xp.float32, copy=False)

G, B = precompute_gram(Thetaz, Y_scaled)

T_eff = Thetaz.shape[0]
G_eff = Thetaz.shape[1]

if GPU_AVAILABLE:
    med = cp.median(Y_scaled, axis=0, keepdims=True)
    mad = cp.median(cp.abs(Y_scaled - med), axis=0, keepdims=True)
    res_std = float(1.4826 * cp.mean(mad))
else:
    med = np.median(Y_scaled, axis=0, keepdims=True)
    mad = np.median(np.abs(Y_scaled - med), axis=0, keepdims=True)
    res_std = 1.4826 * float(np.mean(mad))

print(f"✓ Theta shape = {Theta.shape}, G shape = {G.shape}, B shape = {B.shape}")


# ============================================================
# -------------------- MAIN RUN FUNCTION ---------------------
# ============================================================

def run_for_scale_graph_only(scale, verbose=False):
    """
    Graph-only run:
      1. compute threshold scale
      2. STLSQ solve
      3. refit on support
      4. edge readout using AVERAGE score
      5. sweep graph threshold
      6. build triangles by clique closure
      7. evaluate both graph and triangles
    """
    # This is used as the STLSQ threshold
    thr = scale * (res_std / max(1, math.sqrt(T_eff))) * math.sqrt(2.0 * math.log(max(2, G_eff)))

    if verbose:
        print(f"\n--- Running scale={scale:.4f}, thr={thr:.6e} ---")

    t0 = time.time()

    Xi = solve_stlsq(
        G, B,
        lam_ridge=RIDGE_LAMBDA,
        thr=float(thr),
        n_iter=STLSQ_ITERS,
        keep_const=True
    )

    Xi = refit_on_support(
        G, B, Xi,
        lam_ridge=1e-6,
        keep_const=True
    )

    t1 = time.time()

    sparsity = nnz_summary(Xi)

    # Readout graph with AVERAGE score
    S2, S2_dir = readout_graph_scores_avg(Xi, n)

    # Sweep edge thresholds
    edge_sweep = sweep_edge_thresholds(S2, GT_EDGES_INLINE, qs=EDGE_QS)

    if edge_sweep:
        best_edge = max(edge_sweep, key=lambda z: (z["F1"], z["P"], z["R"]))
        best_q2 = best_edge["q"]
        best_tau2 = best_edge["tau2"]
        edge_metrics = {
            "edge_P": best_edge["P"],
            "edge_R": best_edge["R"],
            "edge_F1": best_edge["F1"],
            "n_edges": best_edge["n_edges"],
        }
    else:
        best_q2 = None
        best_tau2 = np.inf
        edge_metrics = {
            "edge_P": 0.0,
            "edge_R": 0.0,
            "edge_F1": 0.0,
            "n_edges": 0,
        }

    # Build clique complex from thresholded graph
    pred_edges, edge_scores, pred_tris, tri_scores = build_clique_complex_from_graph(S2, best_tau2)

    # Evaluate edges and triangles
    edge_eval = evaluate_set_prediction(pred_edges, GT_EDGES_INLINE)
    tri_eval = evaluate_set_prediction(pred_tris, GT_TRIS_INLINE)

    t2 = time.time()

    return {
        "scale": float(scale),
        "thr": float(thr),
        "best_q2": best_q2,
        "best_tau2": float(best_tau2) if np.isfinite(best_tau2) else np.inf,

        "edge_P": edge_eval["P"],
        "edge_R": edge_eval["R"],
        "edge_F1": edge_eval["F1"],

        "tri_P_clique": tri_eval["P"],
        "tri_R_clique": tri_eval["R"],
        "tri_F1_clique": tri_eval["F1"],

        "n_edges": len(pred_edges),
        "n_triangles": len(pred_tris),

        "nnz_rows": sparsity["nnz_rows"],
        "nnz_params": sparsity["nnz_params"],

        "fit_time_sec": t1 - t0,
        "total_time_sec": t2 - t0,

        # keep these for optional inspection / export
        "Xi": Xi,
        "S2": S2,
        "S2_dir": S2_dir,
        "pred_edges": pred_edges,
        "edge_scores": edge_scores,
        "pred_tris": pred_tris,
        "tri_scores": tri_scores,
    }


# ============================================================
# ---------------------- GRID SEARCH -------------------------
# ============================================================

print("\n🚀 Starting graph-only STLSQ grid search...")

LAMBDA_SCALES = np.linspace(0.5, 2.0, 16)
all_results = []

print(f"{'Scale':<8} | {'EdgeF1':<8} | {'TriF1':<8} | {'Best q2':<8} | {'#Edges':<8} | {'#Tris':<8} | {'Fit(s)':<8}")
print("-" * 80)

for scale in LAMBDA_SCALES:
    res = run_for_scale_graph_only(scale, verbose=False)
    all_results.append(res)

    print(
        f"{res['scale']:<8.3f} | "
        f"{res['edge_F1']:<8.3f} | "
        f"{res['tri_F1_clique']:<8.3f} | "
        f"{str(res['best_q2']):<8} | "
        f"{res['n_edges']:<8d} | "
        f"{res['n_triangles']:<8d} | "
        f"{res['fit_time_sec']:<8.3f}"
    )


# ============================================================
# --------------------- SAVE RESULTS -------------------------
# ============================================================

# Strip large objects before DataFrame export
rows_for_csv = []
for r in all_results:
    rows_for_csv.append({
        "scale": r["scale"],
        "thr": r["thr"],
        "best_q2": r["best_q2"],
        "best_tau2": r["best_tau2"],
        "edge_P": r["edge_P"],
        "edge_R": r["edge_R"],
        "edge_F1": r["edge_F1"],
        "tri_P_clique": r["tri_P_clique"],
        "tri_R_clique": r["tri_R_clique"],
        "tri_F1_clique": r["tri_F1_clique"],
        "n_edges": r["n_edges"],
        "n_triangles": r["n_triangles"],
        "nnz_rows": r["nnz_rows"],
        "nnz_params": r["nnz_params"],
        "fit_time_sec": r["fit_time_sec"],
        "total_time_sec": r["total_time_sec"],
    })

df = pd.DataFrame(rows_for_csv)
out_csv = os.path.join(OUTDIR, "graph_only_stlsq_clique_grid.csv")
df.to_csv(out_csv, index=False)
print(f"\n✅ Saved grid-search results to: {out_csv}")

# Best by edge F1
best_edge_res = max(all_results, key=lambda z: (z["edge_F1"], z["tri_F1_clique"]))
print("\n🏆 Best by edge F1")
print({
    "scale": best_edge_res["scale"],
    "edge_F1": best_edge_res["edge_F1"],
    "tri_F1_clique": best_edge_res["tri_F1_clique"],
    "best_q2": best_edge_res["best_q2"],
    "best_tau2": best_edge_res["best_tau2"],
    "n_edges": best_edge_res["n_edges"],
    "n_triangles": best_edge_res["n_triangles"],
})

# Best by triangle F1 after clique closure
best_tri_res = max(all_results, key=lambda z: (z["tri_F1_clique"], z["edge_F1"]))
print("\n🏆 Best by triangle F1 (clique closure)")
print({
    "scale": best_tri_res["scale"],
    "edge_F1": best_tri_res["edge_F1"],
    "tri_F1_clique": best_tri_res["tri_F1_clique"],
    "best_q2": best_tri_res["best_q2"],
    "best_tau2": best_tri_res["best_tau2"],
    "n_edges": best_tri_res["n_edges"],
    "n_triangles": best_tri_res["n_triangles"],
})

# Save best supports / scores for inspection
best_save = best_tri_res
np.save(os.path.join(OUTDIR, "best_Xi.npy"), to_numpy(best_save["Xi"]))
np.save(os.path.join(OUTDIR, "best_S2_avg.npy"), best_save["S2"])
np.save(os.path.join(OUTDIR, "best_S2_dir.npy"), best_save["S2_dir"])

edges_txt = os.path.join(OUTDIR, "best_edges.txt")
with open(edges_txt, "w") as f:
    f.write("Predicted edges with average scores\n")
    f.write("=" * 50 + "\n")
    for e, s in sorted(best_save["edge_scores"].items(), key=lambda z: (-z[1], tuple(sorted(z[0])))):
        f.write(f"{tuple(sorted(e))}: {s:.8f}\n")

tris_txt = os.path.join(OUTDIR, "best_triangles.txt")
with open(tris_txt, "w") as f:
    f.write("Predicted clique triangles with average edge scores\n")
    f.write("=" * 60 + "\n")
    for tri, s in sorted(best_save["tri_scores"].items(), key=lambda z: (-z[1], tuple(sorted(z[0])))):
        f.write(f"{tuple(sorted(tri))}: {s:.8f}\n")

print(f"\n✅ Saved best Xi, edge scores, and clique triangles in: {OUTDIR}")
print("\nPreview of results:")
print(df.head())